FROM node:23-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production=false
COPY . .
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_FRONTEND_DOMAIN
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_FRONTEND_DOMAIN=${NEXT_PUBLIC_FRONTEND_DOMAIN}
RUN npm run build

FROM node:23-alpine AS production
WORKDIR /app
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
COPY package*.json ./
RUN npm ci --only=production && npm cache clean --force
COPY --from=build --chown=nextjs:nodejs /app /app
WORKDIR /app
USER nextjs

EXPOSE 3000

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_FRONTEND_DOMAIN
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_FRONTEND_DOMAIN=${NEXT_PUBLIC_FRONTEND_DOMAIN}

CMD ["npm", "start"]
